### ISSUE TITLE
calc() incorrectly removes space characters.

### ISSUE THREAD

**Issue by CarcajadaArtificial** [yahiro07/resin#1]
First of all, great project! I'm thankful for you making this. Now this is the bug I found:

Adding the style `width: calc(100% + var(--s-single));` for example, will eventually compile into `width: calc(100%+var(--s-single));` which is invalid CSS. It should preserve the spaces inside a `calc()`.

Thank you.

**Comment by yahiro07** [comment]
Hi,
I noticed your post recently.
Sorry for late reply.

I had local code that is not applied to the published repository, which includes the fix '+' issue for `calc()`.
I've marged them and now the problem should be fixed.
